# Generated by Django 2.2.17 on 2020-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_auto_20201201_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
